[tool.isort]
src_paths = ['.']
profile = 'black'
include_trailing_comma = true
line_length = 120
skip = '.gitignore,.dockerignore,docker-compose.yml,.git,.vscode,env,.env,.venv,venv,env.py'
sections = 'FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
no_lines_before = 'LOCALFOLDER'
multi_line_output = 3
known_django = 'django'
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
balanced_wrapping = true
lines_after_imports = 2
lines_between_sections = 1
split_on_trailing_comma = true


[tool.black]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
